#!/usr/bin/env bash
# scripts/setup-client.sh
# Configure the local Claude Code sandbox-upload skill.
# Writes ~/.config/sandbox-hosting/env (mode 600) from interactive prompts.

set -euo pipefail

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/sandbox-hosting"
config_file="$config_dir/env"

mkdir -p "$config_dir"
chmod 700 "$config_dir"

existing_base=""
existing_user=""
existing_token=""

if [[ -f "$config_file" ]]; then
  # shellcheck disable=SC1090
  source "$config_file"
  existing_base="${SANDBOX_BASE_URL:-}"
  existing_user="${SANDBOX_USER:-}"
  existing_token="${SANDBOX_TOKEN:-}"
  echo "==> Existing config detected at $config_file (will update in place)"
fi

prompt() {
  local label="$1" default="$2"
  local input
  if [[ -n "$default" ]]; then
    read -rp "$label [default: $default]: " input >&2
    input="${input:-$default}"
  else
    read -rp "$label: " input >&2
  fi
  printf '%s' "$input"
}

base_url=$(prompt "Sandbox API base URL (from terraform output api_endpoint)" "${existing_base:-https://abc123.execute-api.ap-northeast-1.amazonaws.com}")
user=$(prompt "Username to claim on upload" "${existing_user:-${USER:-anon}}")

if [[ -n "$existing_token" ]]; then
  read -rp "Replace existing UPLOAD_TOKEN? [y/N]: " replace
  if [[ "${replace,,}" == "y" ]]; then
    token=$(prompt "UPLOAD_TOKEN" "")
  else
    token="$existing_token"
  fi
else
  token=$(prompt "UPLOAD_TOKEN" "")
fi

if [[ -z "$token" ]]; then
  echo "ERROR: token must not be empty" >&2
  exit 1
fi

umask 077
cat > "$config_file" <<EOF
# Generated by scripts/setup-client.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
SANDBOX_BASE_URL="$base_url"
SANDBOX_USER="$user"
SANDBOX_TOKEN="$token"
EOF
chmod 600 "$config_file"

echo
echo "==> Wrote $config_file"
echo "==> Verify with: bash skills/sandbox-upload/scripts/upload.sh list"
